apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  guestbook-name: {{ .Values.config.guestbook_name }}
  backend-uri: {{ .Values.config.backend_uri }}