config:
  guestbook_name: "MyPopRock Festival 1.0"
  backend_uri: "http://backend.ingress.local/guestbook"
image:
  repository: phico/frontend
  tag: "1.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 8006
ingress:
  host: frontend.ingress.local
