secret:
  mongodb_uri: "mongodb://admin:password@mongodb:27017/guestbook?authSource=admin"
image:
  repository: phico/backend
  tag: "2.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 8007
ingress:
  host: backend.ingress.local